# Generated by Django 4.1.7 on 2023-04-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.TextField(default='#9cdcfe'),
        ),
    ]
