# Generated by Django 4.1.7 on 2023-04-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_note_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='textContent',
        ),
    ]
